// ignore_for_file: avoid_print
/// Generates lib/data/emoji_data.dart from GitHub's gemoji dataset
/// supplemented with Unicode CLDR annotation keywords for rich search.
///
/// Run with: dart run scripts/generate_emoji_data.dart
library;

import 'dart:convert';
import 'dart:io';

const _gemojiUrl =
    'https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json';
const _cldrUrl =
    'https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-full/annotations/en/annotations.json';

const _outputPath = 'lib/data/emoji_data.dart';

Future<void> main() async {
  // Fetch both datasets in parallel
  final client = HttpClient();

  print('Fetching gemoji + CLDR data...');
  final gemojiReq = await client.getUrl(Uri.parse(_gemojiUrl));
  final cldrReq = await client.getUrl(Uri.parse(_cldrUrl));
  final gemojiResp = await gemojiReq.close();
  final cldrResp = await cldrReq.close();

  if (gemojiResp.statusCode != 200) {
    print('Failed to fetch gemoji: HTTP ${gemojiResp.statusCode}');
    exit(1);
  }
  if (cldrResp.statusCode != 200) {
    print('Failed to fetch CLDR: HTTP ${cldrResp.statusCode}');
    exit(1);
  }

  final gemojiBody = await gemojiResp.transform(utf8.decoder).join();
  final cldrBody = await cldrResp.transform(utf8.decoder).join();
  client.close();

  final List<dynamic> gemojiRaw = jsonDecode(gemojiBody);

  // Parse CLDR annotations into a map: emoji char → keyword list
  final cldrJson = jsonDecode(cldrBody) as Map<String, dynamic>;
  final annotationsOuter =
      cldrJson['annotations'] as Map<String, dynamic>;
  final annotations =
      annotationsOuter['annotations'] as Map<String, dynamic>;

  final cldrKeywords = <String, List<String>>{};
  for (final entry in annotations.entries) {
    final key = entry.key;
    final value = entry.value as Map<String, dynamic>;
    final defaults = (value['default'] as List?)?.cast<String>() ?? [];
    if (defaults.isNotEmpty) {
      cldrKeywords[key] = defaults;
      // Also store without variation selector for matching
      final stripped = key.replaceAll('\ufe0f', '');
      if (stripped != key) cldrKeywords[stripped] = defaults;
    }
  }

  print(
      'Gemoji: ${gemojiRaw.length} entries, CLDR: ${cldrKeywords.length} annotations');

  // Filter to entries with actual emoji characters
  final entries = <Map<String, dynamic>>[];
  for (final item in gemojiRaw) {
    final map = item as Map<String, dynamic>;
    if (map['emoji'] == null) continue;
    entries.add(map);
  }

  print('Processing ${entries.length} emoji...');

  // Group by category
  final categories = <String, List<Map<String, dynamic>>>{};
  for (final e in entries) {
    final category = (e['category'] as String?) ?? 'Symbols';
    categories.putIfAbsent(category, () => []).add(e);
  }

  // Build the Dart source
  final buf = StringBuffer();
  buf.writeln('// GENERATED FILE — DO NOT EDIT');
  buf.writeln('// Generated by scripts/generate_emoji_data.dart');
  buf.writeln('// Sources: gemoji (GitHub) + CLDR annotations (Unicode)');
  buf.writeln('// ignore_for_file: constant_identifier_names');
  buf.writeln();
  buf.writeln('/// A single emoji entry with metadata for search and display.');
  buf.writeln('class EmojiEntry {');
  buf.writeln('  final String emoji;');
  buf.writeln('  final String name;');
  buf.writeln('  final List<String> keywords;');
  buf.writeln('  final int categoryIndex;');
  buf.writeln();
  buf.writeln(
      '  const EmojiEntry(this.emoji, this.name, this.keywords, this.categoryIndex);');
  buf.writeln('}');
  buf.writeln();

  final categoryNames = categories.keys.toList();
  buf.writeln('/// Emoji category names, indexed by EmojiEntry.categoryIndex.');
  buf.writeln('const emojiCategories = <String>[');
  for (final cat in categoryNames) {
    buf.writeln("  '${_escape(cat)}',");
  }
  buf.writeln('];');
  buf.writeln();

  buf.writeln('/// Representative emoji for each category (for tab icons).');
  buf.writeln('const emojiCategoryIcons = <String>[');
  final iconMap = {
    'Smileys & Emotion': '😀',
    'People & Body': '👋',
    'Animals & Nature': '🐾',
    'Food & Drink': '🍕',
    'Travel & Places': '✈️',
    'Activities': '⚽',
    'Objects': '💡',
    'Symbols': '❤️',
    'Flags': '🏳️',
    'Component': '🔧',
  };
  for (final cat in categoryNames) {
    final icon = iconMap[cat] ?? '⭐';
    buf.writeln("  '$icon',");
  }
  buf.writeln('];');
  buf.writeln();

  // Track keyword coverage stats
  var cldrHits = 0;

  buf.writeln('/// Complete emoji dataset (~${entries.length} entries).');
  buf.writeln('const allEmoji = <EmojiEntry>[');

  for (var ci = 0; ci < categoryNames.length; ci++) {
    final cat = categoryNames[ci];
    final items = categories[cat]!;
    buf.writeln('  // — $cat (${items.length}) —');
    for (final e in items) {
      final emoji = e['emoji'] as String;
      final desc = (e['description'] as String?) ?? '';
      // Merge: gemoji aliases + gemoji tags + CLDR keywords + description words
      final aliases = (e['aliases'] as List?)?.cast<String>() ?? [];
      final tags = (e['tags'] as List?)?.cast<String>() ?? [];
      final cldr = cldrKeywords[emoji] ??
          cldrKeywords[emoji.replaceAll('\ufe0f', '')] ??
          [];
      if (cldr.isNotEmpty) cldrHits++;

      final keywords = <String>{...aliases, ...tags, ...cldr};
      // Add description words as keywords too
      for (final word in desc.toLowerCase().split(RegExp(r'[\s:_-]+'))) {
        if (word.length > 1) keywords.add(word);
      }
      // Remove very short/common words
      keywords.removeWhere((k) => k.length < 2);

      final kwList = keywords.map((k) => "'${_escape(k)}'").join(', ');
      buf.writeln(
          "  EmojiEntry('${_escape(emoji)}', '${_escape(desc)}', [$kwList], $ci),");
    }
  }

  buf.writeln('];');

  final outFile = File(_outputPath);
  await outFile.writeAsString(buf.toString());

  print('Generated $_outputPath');
  print('  ${entries.length} emoji across ${categoryNames.length} categories');
  print('  CLDR keyword coverage: $cldrHits/${entries.length} emoji have CLDR annotations');
  print('  Categories: ${categoryNames.join(', ')}');
}

String _escape(String s) {
  return s
      .replaceAll('\\', '\\\\')
      .replaceAll("'", "\\'")
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r');
}
